# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0003_auto_20171012_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='availabe_supply',
            new_name='available_supply',
        ),
    ]
