# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0004_auto_20171012_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='available_supply',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap_usd',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_1h',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_24h',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_7d',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_btc',
            field=models.DecimalField(decimal_places=10, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='total_supply',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='volume_24h_usd',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
    ]
