# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0004_auto_20171012_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=200, null=True)),
                ('pre_mined_valued', models.DecimalField(decimal_places=10, max_digits=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('algorithm', models.CharField(max_length=200, null=True)),
                ('fully_premined', models.DecimalField(decimal_places=10, max_digits=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('coin_id', models.IntegerField(null=True)),
                ('proof_type', models.CharField(max_length=200, null=True)),
                ('sponsored', models.DecimalField(decimal_places=10, max_digits=200, null=True)),
                ('sort_order', models.IntegerField(null=True)),
                ('total_coin_supply', models.DecimalField(decimal_places=10, max_digits=200, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('total_coins_free_float', models.DecimalField(decimal_places=10, max_digits=200, null=True)),
                ('symbol', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='available_supply',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap_usd',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_1h',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_24h',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_7d',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_btc',
            field=models.DecimalField(decimal_places=10, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='total_supply',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='volume_24h_usd',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
    ]
