# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0006_auto_20171018_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocompare',
            name='fully_premined',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocompare',
            name='total_coin_supply',
            field=models.IntegerField(null=True),
        ),
    ]
