# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0008_auto_20171018_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocompare',
            name='fully_premined',
        ),
        migrations.RemoveField(
            model_name='cryptocompare',
            name='pre_mined_valued',
        ),
        migrations.RemoveField(
            model_name='cryptocompare',
            name='sponsored',
        ),
        migrations.RemoveField(
            model_name='cryptocompare',
            name='total_coins_free_float',
        ),
    ]
