# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0009_auto_20171018_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocompare',
            name='total_coin_supply',
            field=models.IntegerField(null=True),
        ),
    ]
