# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0012_auto_20171018_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocompare',
            name='coin_id',
            field=models.IntegerField(null=True),
        ),
    ]
