# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0014_auto_20171019_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocompare',
            name='market_cap_usd',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='cryptocompare',
            name='percent_change_24_hours',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='cryptocompare',
            name='supply',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cryptocompare',
            name='usd_change_24_hours',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
    ]
