# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0015_auto_20171019_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocompare',
            name='supply',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
    ]
