# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0016_auto_20171019_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocompare',
            name='market_cap_usd',
        ),
        migrations.RemoveField(
            model_name='cryptocompare',
            name='percent_change_24_hours',
        ),
        migrations.RemoveField(
            model_name='cryptocompare',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='cryptocompare',
            name='usd_change_24_hours',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
