# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0017_auto_20171019_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
