# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0018_news'),
        ('bitboard', '0005_auto_20171023_1938'),
    ]

    operations = [
    ]
