# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0019_merge_20171027_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
