# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitboard', '0020_news_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
